### 동기적 실행
POST http://localhost:8080/batch
Content-Type: application/json

{
  "id" : "leaven"
}

### 비동기적 실행
POST http://localhost:8080/async/batch
Content-Type: application/json

{
  "id" : "leaven"
}